name: main checks
on:
  push:
    branches:
      - main

env:
  SECRET_KEY: insecure_test_key

jobs:
  run-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag pythonoperatorframework-io .

      - name: Run image
        run: |
          docker run -d -p 80:80 --env SECRET_KEY=insecure_secret_key pythonoperatorframework-io
          sleep 1
          curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost
  run-dotrun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dotrun
        run: |
          sudo snap install dotrun
          sudo chown root:root /
      - name: Install dependencies
        run: dotrun install

      - name: Build assets
        run: dotrun build

      - name: Test site
        run: dotrun & curl --head --fail --retry-delay 1 --retry 30 --retry-connrefused http://localhost:8047

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo pip3 install flake8 black
      - name: Lint python
        run: yarn lint-python

  lint-scss:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint scss
        run: yarn lint-scss

  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: |
          sudo apt-get update && sudo apt-get install --yes python3-setuptools
          sudo pip3 install -r requirements.txt
      - name: Install dependencies
        run: sudo pip3 install coverage

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Build resources
        run: yarn build

      - name: Run tests with coverage
        run: coverage run  --source=. -m unittest discover tests
